# Generated by Django 3.2.2 on 2021-05-13 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('chassisNo', models.CharField(max_length=50)),
                ('IMEI', models.CharField(max_length=50)),
                ('vehicleRegNo', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=30)),
                ('phoneNo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicleDetails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datalogger.vehicleregister'),
            preserve_default=False,
        ),
    ]
