# Generated by Django 3.2.2 on 2021-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0002_auto_20210513_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicleDetails',
        ),
        migrations.AlterField(
            model_name='vehicleregister',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
