# Generated by Django 3.2.2 on 2021-05-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0004_delete_vehicleregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('chassisNo', models.CharField(max_length=50)),
                ('IMEI', models.CharField(max_length=50)),
                ('vehicleRegNo', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=30)),
                ('phoneNo', models.IntegerField()),
            ],
        ),
    ]
