# Generated by Django 3.2.2 on 2021-05-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0005_vehicledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='IMEI',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='chassisNo',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='vehicleRegNo',
            field=models.CharField(max_length=10),
        ),
    ]
