# Generated by Django 3.2.2 on 2021-05-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datalogger', '0007_vehicle_vehicledetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datalogger.vehicledata', to_field='vehicleRegNo'),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='vehicleRegNo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
